<?php

namespace AppBundle\Repository;

/**
 * RepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepRepository extends \Doctrine\ORM\EntityRepository
{
}
