<?php

namespace AppBundle\Repository;

/**
 * SalesOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesOrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
